color: null
description: null
fieldLayouts:
  ffd6765e-59d2-44ea-9afe-fe0fcfa15059:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T16:37:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76d6cdc7-f69d-4c30-9139-060120bf0469 # Component URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e630321-af7e-4946-8db1-d7d9d30d12c2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44affdc2-98c1-4727-a3d1-c5de8970abb3
        userCondition: null
handle: backgroundVideo
hasTitleField: false
icon: null
name: 'Background Video'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
