color: null
description: null
fieldLayouts:
  4ca96155-f9e2-4ca8-b483-1b21aa770cab:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-06T05:06:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394b8286-4d39-4831-aea8-a4dcf7636059 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62aa9b73-412d-4464-aaa5-aca00f6c7c48
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 530f8159-a43b-4d17-a12f-75dfb942a88c
        userCondition: null
handle: backgroundColor
hasTitleField: false
icon: null
name: 'Background Color'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
