color: null
description: null
fieldLayouts:
  d7cb0d4a-c464-4006-8f6d-765154248ef0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-05T05:18:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a37e8654-084a-40d3-8ecb-f485a7dab8e4 # Event Calendar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1e50198-8bbf-48ff-a7d7-d9f3fa989f90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1848e990-9537-4e39-ad5a-410354703cb1
        userCondition: null
handle: eventCalendar
hasTitleField: false
icon: null
name: 'Event Calendar'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
