color: null
description: null
fieldLayouts:
  bf5beab4-c397-4285-9dac-e119a763fe32:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-07T22:18:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: af399b87-d5e8-4c76-ae60-c32755a1d23b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0431b49d-8693-4ea3-aef4-4c6321566f21
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-07T22:20:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 92489f8e-11e6-4f01-bc0e-e09fee99ffee # H3 Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d938f1a7-2e79-4ae0-b4b1-28dc5f47280c
            userCondition: null
            warning: null
            width: 100
        name: h3
        uid: 183273af-d5a1-434f-a483-04a3a2930a96
        userCondition: null
handle: headings
hasTitleField: true
icon: null
name: headings
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
