color: null
description: null
fieldLayouts:
  843224f5-0a96-492e-9b71-ea4d436069e7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T22:33:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 108a2396-e640-4a00-abd3-0ee3b582480b # Vertical Padding (Pixels)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c73904a9-cd62-40f8-907f-0890649aa6a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80114ebe-2130-4d08-aa0a-c79661f3edc6
        userCondition: null
handle: verticalPadding
hasTitleField: false
icon: null
name: 'Vertical Padding'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
