altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a0718112-928d-4445-bf93-492584534364:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-03T22:03:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 10bfb083-481f-45de-8186-8f20a67f604f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b6e8cbd-d89f-4f64-bf0a-69dc698f26b9
        userCondition: null
fs: cloudinary
handle: images
name: Images
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: cloudinary
transformSubpath: ''
