childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 17a07c7f-6fed-4095-998b-47234e1f0121 # Background Color
field: 22b3fc84-2fbb-4ddc-9ed2-2389dd334699 # Regular Page Builder
fieldLayouts:
  9894140b-2faf-457e-82d4-f0a1069f5926:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-06T05:06:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394b8286-4d39-4831-aea8-a4dcf7636059 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bff3334d-0313-414c-b2e2-a939ce50f9a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4784dcbc-5eef-4d1b-af24-d79687fac26b
        userCondition: null
group: null
groupChildBlockTypes: true
handle: backgroundColor
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Background Color'
topLevel: false
