childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 04f6945e-a804-44ba-88dc-2425bfa5a7c7 # Event Calendar
field: 2ea47bbc-6f12-44ad-b685-61b5c862a07d # Page Builder
fieldLayouts:
  20c38b5e-215e-4835-8e1f-d936ae0686ea:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-05T05:18:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a37e8654-084a-40d3-8ecb-f485a7dab8e4 # Event Calendar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ad7d998-8014-4ab9-bd6c-278ffc0bb8f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 97e1e475-d642-4552-8534-9e7250da89d3
        userCondition: null
group: null
groupChildBlockTypes: true
handle: eventCalendar
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Event Calendar'
topLevel: false
