childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 9f160980-07d0-466e-ae0a-fc68ed8dfeeb # H1 Heading
field: 22b3fc84-2fbb-4ddc-9ed2-2389dd334699 # Regular Page Builder
fieldLayouts:
  2a2b34d4-b660-4043-a35f-9148c17570b1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-06T06:06:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd4fe4c2-b508-4298-9820-b4b13cab9e32 # H1 Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 394bb722-88bb-4669-ae0a-4cc40a1d1b8e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b9482f2-17cb-40b2-843f-daca44749e4b
        userCondition: null
group: null
groupChildBlockTypes: true
handle: h1Heading
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'H1 Heading'
topLevel: false
