childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 9a82a758-92a8-43b8-b084-e6ae5784cb7e # Show In Nav
field: 22b3fc84-2fbb-4ddc-9ed2-2389dd334699 # Regular Page Builder
fieldLayouts:
  14b2f5ad-a4d9-44cf-a698-aa72e7456512:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-10T23:32:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: be024036-351c-423d-9cf7-6855dddf23c5 # Show In Nav
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eb2ef96-fe54-4a10-8976-ae0c8439c3dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc7889b6-1193-40a5-a406-008d25fa595e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: showInNav
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 1
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Show In Nav'
topLevel: true
