childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 9a82a758-92a8-43b8-b084-e6ae5784cb7e # Show In Nav
field: cb47f35f-ec0a-4066-a291-2c2e8547ab57 # Sponsors
fieldLayouts:
  b0402b54-2934-4510-9a87-ba2fc1fbeafa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-10T23:32:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: be024036-351c-423d-9cf7-6855dddf23c5 # Show In Nav
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56f7e514-2ca5-4f18-87c1-47a0403719ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9cdf6610-2239-48dd-8c4f-5f7157ff0f59
        userCondition: null
group: null
groupChildBlockTypes: true
handle: showInNav
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 1
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Show In Nav'
topLevel: true
