childBlocks:
  - column
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 22b3fc84-2fbb-4ddc-9ed2-2389dd334699 # Regular Page Builder
group: null
groupChildBlockTypes: true
handle: twoColumnHero
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 2
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 2
minSiblingBlocks: 0
name: 'Two Column Hero'
topLevel: true
