childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: 6a583cf4-f6f4-4180-a6ee-eeb4396aeb97 # Vertical Padding
field: 22b3fc84-2fbb-4ddc-9ed2-2389dd334699 # Regular Page Builder
fieldLayouts:
  e7de9ef0-09b1-4e66-bf08-d760d520df57:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-08T22:33:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 108a2396-e640-4a00-abd3-0ee3b582480b # Vertical Padding (Pixels)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4140c3c-170b-4a5e-8d13-10740f5b258d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff930421-43af-4775-b18f-cbfb3aa50d37
        userCondition: null
group: null
groupChildBlockTypes: true
handle: verticalPadding
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Vertical Padding'
topLevel: true
