columnSuffix: null
handle: backgroundColor
instructions: null
name: 'Background Color'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
