columnSuffix: null
handle: centered
instructions: null
name: Centered
searchable: false
settings:
  default: false
  offLabel: 'Not Centered'
  onLabel: Centered
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
