columnSuffix: null
handle: imageDarkness
instructions: null
name: 'Image Darkness'
searchable: false
settings:
  defaultValue: null
  max: 1
  min: 0
  step: 0.1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
