columnSuffix: null
handle: verticalPadding
instructions: null
name: 'Vertical Padding (Pixels)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
